spring:
  application:
    name: greeting-service
  cloud:
    config:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greeting-service:
  greeting: "Olá"
  default-value: "Application QA - Atualização para testar @RefreshScope"
